# Generated by Django 5.2.7 on 2025-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0003_osoba_data_dodania_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mezczyzna'), (3, 'Inna')], default=3),
        ),
    ]
